name: xyz
favicon: null
layout_spectrum: 0.3630794305354357
typography_spectrum: 0.8618357668165118
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.04365500411950052
  lightness: 0.6309319282881916
  saturation: 0.3208493669517338
  rhythmicContrast: 0.9186421604827046
purpose: []
